name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-container:
    name : Build docker container 

    runs-on: ubuntu-latest

    steps:
    - name : Checkout code
      uses : actions/checkout@v3
    - name : Login to Docker Hub
      uses : docker/login-actions@v1
      with:
        username: ${{secrets.ID_DOCKER_HUB }}
        password: ${{secrets.PASSWD_DOCKER_HUB}}
    - name : Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: suveta/tp1devops:1.0.0
         

